CREATE TABLE IF NOT EXISTS tbl_finalized_salary_records (
  id SERIAL PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES tbl_employees(id) ON DELETE RESTRICT,
  month INT NOT NULL CHECK (month BETWEEN 1 AND 12),
  year INT NOT NULL,
  present_days NUMERIC(8, 2) NOT NULL DEFAULT 0,
  final_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT uq_finalized_salary_employee_month UNIQUE (employee_id, month, year)
);

CREATE TABLE IF NOT EXISTS tbl_government_salary_records (
  id SERIAL PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES tbl_employees(id) ON DELETE RESTRICT,
  month INT NOT NULL CHECK (month BETWEEN 1 AND 12),
  year INT NOT NULL,
  source_present_days NUMERIC(8, 2) NOT NULL DEFAULT 0,
  present_days NUMERIC(8, 2) NOT NULL DEFAULT 0,
  total_days INT NOT NULL,
  additional_absent_days INT NOT NULL DEFAULT 0,
  basic_salary NUMERIC(14, 2) NOT NULL DEFAULT 0,
  updated_basic_salary NUMERIC(14, 2) NOT NULL DEFAULT 0,
  hra NUMERIC(14, 2) NOT NULL DEFAULT 0,
  conveyance NUMERIC(14, 2) NOT NULL DEFAULT 0,
  ot_allowance NUMERIC(14, 2) NOT NULL DEFAULT 0,
  incentive NUMERIC(14, 2) NOT NULL DEFAULT 0,
  total_earnings NUMERIC(14, 2) NOT NULL DEFAULT 0,
  pf NUMERIC(14, 2) NOT NULL DEFAULT 0,
  pfvol NUMERIC(14, 2) NOT NULL DEFAULT 0,
  esi NUMERIC(14, 2) NOT NULL DEFAULT 0,
  tds NUMERIC(14, 2) NOT NULL DEFAULT 0,
  advance_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  other_deduction NUMERIC(14, 2) NOT NULL DEFAULT 0,
  plwf NUMERIC(14, 2) NOT NULL DEFAULT 0,
  other_deductions NUMERIC(14, 2) NOT NULL DEFAULT 0,
  professional_tax NUMERIC(14, 2) NOT NULL DEFAULT 0,
  total_deductions NUMERIC(14, 2) NOT NULL DEFAULT 0,
  net_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  saved_final_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT uq_government_salary_employee_month UNIQUE (employee_id, month, year)
);
